spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
lambda.welcomeEmail.url=${WELCOME_EMAIL_LAMBDA_URL}
lambda.weeklySummary.url=${WEEKLY_SUMMARY_LAMBDA_URL}
